### ISSUE TITLE
v2 roadmap

### ISSUE THREAD

**Issue by n4o847** [n4o847/compile-time-typescript#4]
- [ ] Make it available as a library
- [ ] Make `typescript` a peer dependency
- [ ] Change interfaces
  - [ ] Do not use `Buffer` for input and output
  - [ ] #3 ?
